architecture: replication
global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/mysql
  tag: "sha256-d0b33f06937bfac858ac9780be94ceca872543b30319f80c156bcb243915d1de"

# enable init container that changes the owner and group of the persistent volume mountpoint to runAsUser:fsGroup
volumePermissions:
  enabled: true

secondary:
  # 1 primary and 2 secondary replicas
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for EKS volumes
    storageClass: gp2

auth:
  rootPassword: secret-root-pass
  database: my-app-db
  username: my-user
  password: my-pass
