architecture: replication
global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/mysql
  tag: "8.0"


primary:
  persistence:
    enabled: true
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
    size: 8Gi

secondary:
  # 1 primary and 2 secondary replicas
  replicaCount: 2
  persistence:
    accessModes: ["ReadWriteOnce"]
    # storage class for EKS volumes
    storageClass: gp2
    size: 8Gi

auth:
  rootPassword: secret-root-pass
  database: my-app-db
  username: my-user
  password: my-pass
